#!/bin/sh
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright 2019 Heinrich Schuchardt <xypron.glpk@gmx.de>

set -e

export_gpio() {	
	for i in 484 478 479
	do
		echo $i > /sys/class/gpio/export || true
		echo 1 > /sys/class/gpio/gpio$i/active_low
		echo out > /sys/class/gpio/gpio$i/direction
		echo 0 > /sys/class/gpio/gpio$i/value
		chown root:piwsrb /sys/class/gpio/gpio$i/value
		chmod 664 /sys/class/gpio/gpio$i/value
	done
}

unexport_gpio() {	
	for i in 484 478 479
	do
		echo $i > /sys/class/gpio/unexport
	done
}

status_gpio() {
	n=1
	for i in 484 478 479
	do
		echo -n "Relay $n: "
		cat /sys/class/gpio/gpio$i/value
		n=$((n+1))
	done
}

usage() {
	echo Control WaveShare RPi Relay Board
	echo Usage:
	echo relay-card export   - enable GPIOs
	echo relay-card unexport - disable GPIOs
	echo relay-card off      - switch relay 1 off
	echo relay-card on       - switch relay 1 on
	echo relay-card reset    - switch relay 2 on for 1 second
	echo relay-card status   - display relay status
}

main() {
	case "$1" in
	export)
		export_gpio
		;;
	unexport)
		unexport_gpio
		;;
	on)
		echo 1 > /sys/class/gpio/gpio484/value
		;;
	off)
		echo 0 > /sys/class/gpio/gpio484/value
		;;
	reset)
		echo 1 > /sys/class/gpio/gpio478/value
		sleep 1
		echo 0 > /sys/class/gpio/gpio478/value
		;;
	status)
		status_gpio
		;;
	*)
		usage
		exit 1;
		;;
	esac
}

main "$@"
